title: "Coursite"
description: "Mes formations en ligne — DevOps, Cloud, Scripting"
url: "https://gooseppr.github.io"
baseurl: "/GevOps_LC"
theme: minima
header_pages:
  - index.md
include:
  - _includes
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - courses/**/PLAN.md

defaults:
  - scope:
      path: "modules"
      type: "pages"
    values:
      render_with_liquid: false
